# hoisting behavior
hoist: true
shamefullyHoist: true

# dependency behavior
dedupeDirectDeps: true

ignoreWorkspaceRootCheck: true
shellEmulator: true

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
