name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10.33.2
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "pnpm"

      - run: pnpm install --shamefully-hoist=true
      - run: pnpm format:check
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
